config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :accounts,
                 path: '/',
                 path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
                 },
                 sign_out_via: [:delete, :get]

      resources :schools, only: [:index]
      resource :parents, only: [:show, :update]
      resources :children, only: [:index, :show, :create, :update, :destroy] do
        post :pair
        post :board
      end
      resources :bookings, only: [:index, :show, :create, :update] do
        post :cancel
        post :finish
        post :approach
      end
      resources :meeting_points, only: [:index]
      resources :devices, only: [:create]
    end
  end

  resources :dashboards, only: [:index]

  scope :accounts do
    resource :invitation, controller: 'invitations', only: [:new, :create, :update] do
      collection do
        get :accept, action: :edit
      end
    end
  end

  namespace :pages do
    get :home
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :parent
  belongs_to :school
  belongs_to :meeting_point
  has_and_belongs_to_many :children

  enum status: [:active, :cancelled, :finished]
  enum trip_type: [:meeting_point_to_school, :school_to_meeting_point, :both_ways]

  validates_presence_of :parent, :school, :children, :status, :trip_type, :date

  def cancel!
    self.cancelled!
  end

  def finish!
    # :nocov:
    self.finished!
    # :nocov:
  end
end

app/controllers/api/v1/bookings_controller.rb
class API::V1::BookingsController < API::V1::ApplicationController
  include ChildAuthorization

  before_action :set_booking, only: [:show, :update, :cancel, :approach, :finish]
  skip_before_action :authenticate_account!, only: [:index, :show, :approach, :finish]
  before_action :authenticate_child!, only: [:index, :show]

  def index
    authorize self
    @bookings = (@parent || @child).bookings.active
    render json: @bookings
  end

  def show
    authorize @booking, policy_class: self.class.policy_class
    render json: @booking
  end

  def create
    @booking = Booking.new(booking_params)
    authorize @booking, policy_class: self.class.policy_class
    @booking = BookingService.create(@booking, current_account)
    if @booking.errors.empty?
      render json: @booking, status: :created
    else
      render json: @booking.errors, status: :unprocessable_entity
    end
  end

  def update
    authorize @booking, policy_class: self.class.policy_class
    if @booking.update(booking_params)
      render json: @booking, status: :ok
    else
      render json: @booking.errors, status: :unprocessable_entity
    end
  end

  def cancel
    authorize @booking, policy_class: self.class.policy_class
    @booking.cancel!
    render json: {}, status: :ok
  end

  def approach
    # :nocov:
    # send notification to the parents
    PushNotificationJob.perform_later(@booking.parent, title: "Bus for #{@booking.children.map(&:name).to_sentence} is approaching!", body: 'Prepare your children')
    # :nocov:
  end

  def finish
    # :nocov:
    # send notification to the parents
    PushNotificationJob.perform_later(@booking.parent, title: "Bus for #{@booking.children.map(&:name).to_sentence} is arrived at the destination!", body: 'They arrived safely')
    @booking.finish!
    # :nocov:
  end

  private

  def set_booking
    @booking = Booking.find(params[:id] || params[:booking_id])
  end

  def booking_params
    params.require(:booking).permit(:date, :trip_type, :meeting_point_id, child_ids: [])
  end

  def self.policy_class
    API::BookingPolicy
  end
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>