config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :accounts,
                 path: '/',
                 path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
                 },
                 sign_out_via: [:delete, :get]

      resources :schools, only: [:index]
      resource :parents, only: [:show, :update]
      resources :children, only: [:index, :show, :create, :update, :destroy] do
        post :pair
        post :board
      end
      resources :bookings, only: [:index, :show, :create, :update] do
        post :cancel
        post :finish
        post :approach
      end
      resources :meeting_points, only: [:index]
      resources :devices, only: [:create]
    end
  end

  resources :dashboards, only: [:index]

  scope :accounts do
    resource :invitation, controller: 'invitations', only: [:new, :create, :update] do
      collection do
        get :accept, action: :edit
      end
    end
  end

  namespace :pages do
    get :home
  end
end

app/models/school.rb
class School < ApplicationRecord
  has_many :accounts, as: :entity
  has_and_belongs_to_many :parents, join_table: :school_memberships
  has_many :children
  has_many :bookings

  geocoded_by :address
  after_validation :geocode, unless: -> { Rails.env.test? }

  validates_presence_of :name, :street, :street_number, :zipcode, :town, :phone_no

  def address
    ["#{street} #{street_number}", zipcode, town].compact.join(', ')
  end
end

app/controllers/api/v1/schools_controller.rb
class API::V1::SchoolsController < API::V1::ApplicationController
  def index
    authorize self
    render json: current_account.entity.schools
  end

  private

  def self.policy_class
    API::SchoolPolicy
  end
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schools</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>