config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :accounts,
                 path: '/',
                 path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
                 },
                 sign_out_via: [:delete, :get]

      resources :schools, only: [:index]
      resource :parents, only: [:show, :update]
      resources :children, only: [:index, :show, :create, :update, :destroy] do
        post :pair
        post :board
      end
      resources :bookings, only: [:index, :show, :create, :update] do
        post :cancel
        post :finish
        post :approach
      end
      resources :meeting_points, only: [:index]
      resources :devices, only: [:create]
    end
  end

  resources :dashboards, only: [:index]

  scope :accounts do
    resource :invitation, controller: 'invitations', only: [:new, :create, :update] do
      collection do
        get :accept, action: :edit
      end
    end
  end

  namespace :pages do
    get :home
  end
end

app/models/parent.rb
class Parent < ApplicationRecord
  has_one :account, as: :entity
  has_and_belongs_to_many :schools, join_table: :school_memberships
  has_and_belongs_to_many :children
  has_many :devices, as: :owner, dependent: :destroy
  has_many :bookings

  validates_presence_of :first_name, :last_name, :street, :street_number, :zipcode, :town, :phone_no
end

app/controllers/api/v1/parents_controller.rb
class API::V1::ParentsController < API::V1::ApplicationController
  def show
    authorize self
    render json: @parent
  end

  def update
    authorize self
    if @parent.update(parent_params)
      render json: @parent, status: :ok
    else
      render json: @parent.errors, status: :unprocessable_entity
    end
  end

  private

  def parent_params
    params.require(:parent).permit(:first_name, :last_name, :street, :street_number, :zipcode, :town, :phone_no)
  end

  def self.policy_class
    API::ParentPolicy
  end
end

app/views/parents/_form.html.erb
<%= form_with(model: parent, local: true) do |form| %>
  <% if parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Show', @parent %> |
<%= link_to 'Back', parents_path %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parents</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form', parent: @parent %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>