config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :accounts,
                 path: '/',
                 path_names: {
                   sign_in: 'login',
                   sign_out: 'logout'
                 },
                 sign_out_via: [:delete, :get]

      resources :schools, only: [:index]
      resource :parents, only: [:show, :update]
      resources :children, only: [:index, :show, :create, :update, :destroy] do
        post :pair
        post :board
      end
      resources :bookings, only: [:index, :show, :create, :update] do
        post :cancel
        post :finish
        post :approach
      end
      resources :meeting_points, only: [:index]
      resources :devices, only: [:create]
    end
  end

  resources :dashboards, only: [:index]

  scope :accounts do
    resource :invitation, controller: 'invitations', only: [:new, :create, :update] do
      collection do
        get :accept, action: :edit
      end
    end
  end

  namespace :pages do
    get :home
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Home", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav mr-auto">
        <% if current_account&.admin? || current_account&.school? %>
        <%= link_to "Invite User", new_invitation_path, class: 'nav-item nav-link' %>
        <% end %>
      </div>
      <div class="navbar-nav">
        <% if current_account %>
        <span class="nav-item nav-link">
          Welcome,
          <%= current_account.entity.try(:name) || current_account.entity.try(:first_name) || current_account.email %>
        </span>
        <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: 'nav-item nav-link' %>
        <% else %>
        <%= link_to "Sign In", new_account_session_path, class: 'nav-item nav-link' %>
        <% end %>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Schubo" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Schubo" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>